In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
x = pd.DataFrame(np.random.randn(20,5), columns = ['one','two','three','four','five'])
x

         one       two     three      four      five
0   2.613255  0.647178  0.874626  0.499653  0.755423
1   0.429194 -0.087207  1.775525  0.011060 -0.053880
2  -0.974435 -0.964163 -0.039724  0.263177 -0.650329
3  -0.159031  1.184442 -1.255795  1.204042  0.037800
4  -2.245577  0.207683  0.647301 -0.395489  0.641839
5  -0.139479 -1.578953  0.852754 -0.531360  0.382977
6   0.624620  0.595421  1.751955 -1.562729 -0.023369
7   0.510834 -0.762499 -0.896322 -0.746471 -0.401713
8   0.609924  0.306034 -0.351257  1.188752 -2.242050
9   1.816497 -0.288959 -1.256684 -1.264217  0.003309
10 -1.375319  0.629401  1.533394 -0.996304  0.781416
11  1.111002  0.794082 -0.926558 -1.357599 -0.308899
12 -1.189208 -1.475273  0.027998 -2.390132  0.438361
13 -0.764703 -0.282951 -2.039827 -0.845290 -0.896344
14 -0.926601  1.237093  0.000194  1.890172  0.542292
15  0.391271  0.437369  0.962748 -1.998058  0.626140
16  1.366873 -0.902806 -0.956908 -0.738715 -0.537408
17 -0.540217  0.826547 -0.131133  0.875636  1.362872
18  0.589566 -0.935678 -1.043393 -1.661300  0.074151
19 -0.071128  0.487684  0.772320 -0.613188 -1.793750

In [7]:
x1 = pd.DataFrame(np.random.randn(10,5), columns = ['one','two','three','four','five'])
x1

        one       two     three      four      five
0  1.517685 -1.533004 -0.658799  1.692529 -0.785665
1 -1.473093  0.291553  0.940191 -0.277586 -1.066530
2  0.520529  0.747865  0.359396 -0.033049 -1.631507
3  1.127659  0.047670 -0.138116  2.902522 -2.104418
4  0.081861 -0.809930  0.090060  0.174937 -2.710482
5  0.965291  0.892327 -0.353919 -0.143839  0.599215
6 -0.199274  0.803755  0.866481 -1.796133 -0.956560
7  0.151654  0.950196 -1.258706 -0.353428 -0.647218
8 -2.176171 -0.962949 -0.936329 -0.557776 -1.124153
9  0.702399  0.222038 -1.392189 -1.369690 -1.046401

In [9]:
pieces = [x,x1]

In [13]:
X = pd.concat(pieces, ignore_index = True)
X

         one       two     three      four      five
0   2.613255  0.647178  0.874626  0.499653  0.755423
1   0.429194 -0.087207  1.775525  0.011060 -0.053880
2  -0.974435 -0.964163 -0.039724  0.263177 -0.650329
3  -0.159031  1.184442 -1.255795  1.204042  0.037800
4  -2.245577  0.207683  0.647301 -0.395489  0.641839
5  -0.139479 -1.578953  0.852754 -0.531360  0.382977
6   0.624620  0.595421  1.751955 -1.562729 -0.023369
7   0.510834 -0.762499 -0.896322 -0.746471 -0.401713
8   0.609924  0.306034 -0.351257  1.188752 -2.242050
9   1.816497 -0.288959 -1.256684 -1.264217  0.003309
10 -1.375319  0.629401  1.533394 -0.996304  0.781416
11  1.111002  0.794082 -0.926558 -1.357599 -0.308899
12 -1.189208 -1.475273  0.027998 -2.390132  0.438361
13 -0.764703 -0.282951 -2.039827 -0.845290 -0.896344
14 -0.926601  1.237093  0.000194  1.890172  0.542292
15  0.391271  0.437369  0.962748 -1.998058  0.626140
16  1.366873 -0.902806 -0.956908 -0.738715 -0.537408
17 -0.540217  0.826547 -0.131133  0.875636  1.362872
18  0.589566 -0.935678 -1.043393 -1.661300  0.074151
19 -0.071128  0.487684  0.772320 -0.613188 -1.793750
20  1.517685 -1.533004 -0.658799  1.692529 -0.785665
21 -1.473093  0.291553  0.940191 -0.277586 -1.066530
22  0.520529  0.747865  0.359396 -0.033049 -1.631507
23  1.127659  0.047670 -0.138116  2.902522 -2.104418
24  0.081861 -0.809930  0.090060  0.174937 -2.710482
25  0.965291  0.892327 -0.353919 -0.143839  0.599215
26 -0.199274  0.803755  0.866481 -1.796133 -0.956560
27  0.151654  0.950196 -1.258706 -0.353428 -0.647218
28 -2.176171 -0.962949 -0.936329 -0.557776 -1.124153
29  0.702399  0.222038 -1.392189 -1.369690 -1.046401

In [18]:
x3 = pd.DataFrame(np.random.randn(30,2), columns = ['six','seven'])

In [19]:
x3

         six     seven
0  -0.375150  2.161305
1  -0.387925 -0.155680
2   0.028078 -0.043984
3   0.129494 -0.225265
4   0.567255 -0.619956
5  -0.417155 -1.130191
6   1.565774  1.084594
7  -1.335019  2.515641
8   0.336238  0.515763
9  -1.490686  1.908603
10 -0.815761 -2.689378
11  1.132700 -0.011005
12 -1.479730 -0.720849
13  1.483281 -0.868241
14 -0.683493  0.234903
15 -0.728329  0.738692
16  0.084038  1.390776
17 -1.124256  2.584634
18  0.188416 -0.554757
19 -1.490123  1.248048
20  0.831192  1.631030
21  1.753843 -0.748139
22  0.101974 -0.187903
23  0.577898 -0.195543
24 -0.208301 -0.654462
25  0.257268 -0.726120
26  0.203072  0.008582
27 -1.431059  0.720265
28  1.460749 -2.265406
29  0.970916  0.371359

In [28]:
c = pd.merge(X, x3, how = 'left', left_on = 'one', right_on = 'two')

KeyError: 'two'

In [26]:
X

         one       two     three      four      five
0   2.613255  0.647178  0.874626  0.499653  0.755423
1   0.429194 -0.087207  1.775525  0.011060 -0.053880
2  -0.974435 -0.964163 -0.039724  0.263177 -0.650329
3  -0.159031  1.184442 -1.255795  1.204042  0.037800
4  -2.245577  0.207683  0.647301 -0.395489  0.641839
5  -0.139479 -1.578953  0.852754 -0.531360  0.382977
6   0.624620  0.595421  1.751955 -1.562729 -0.023369
7   0.510834 -0.762499 -0.896322 -0.746471 -0.401713
8   0.609924  0.306034 -0.351257  1.188752 -2.242050
9   1.816497 -0.288959 -1.256684 -1.264217  0.003309
10 -1.375319  0.629401  1.533394 -0.996304  0.781416
11  1.111002  0.794082 -0.926558 -1.357599 -0.308899
12 -1.189208 -1.475273  0.027998 -2.390132  0.438361
13 -0.764703 -0.282951 -2.039827 -0.845290 -0.896344
14 -0.926601  1.237093  0.000194  1.890172  0.542292
15  0.391271  0.437369  0.962748 -1.998058  0.626140
16  1.366873 -0.902806 -0.956908 -0.738715 -0.537408
17 -0.540217  0.826547 -0.131133  0.875636  1.362872
18  0.589566 -0.935678 -1.043393 -1.661300  0.074151
19 -0.071128  0.487684  0.772320 -0.613188 -1.793750
20  1.517685 -1.533004 -0.658799  1.692529 -0.785665
21 -1.473093  0.291553  0.940191 -0.277586 -1.066530
22  0.520529  0.747865  0.359396 -0.033049 -1.631507
23  1.127659  0.047670 -0.138116  2.902522 -2.104418
24  0.081861 -0.809930  0.090060  0.174937 -2.710482
25  0.965291  0.892327 -0.353919 -0.143839  0.599215
26 -0.199274  0.803755  0.866481 -1.796133 -0.956560
27  0.151654  0.950196 -1.258706 -0.353428 -0.647218
28 -2.176171 -0.962949 -0.936329 -0.557776 -1.124153
29  0.702399  0.222038 -1.392189 -1.369690 -1.046401